from enum import StrEnum

from grim.stats import Tweak


class Attribute(StrEnum):
    STR = "Strength"
    DEX = "Dexterity"


class Save(StrEnum):
    PO = "Poison"


def test_tweaks() -> None:
    # tweaks have autogenerated unique ids useful in interactive generation of characters
    str1 = Tweak(cat=Attribute, stat=Attribute.STR, val=1)
    strm1 = Tweak(cat=Attribute, stat=Attribute.STR, val=-1)
    s1 = Tweak(cat=Save, stat=Save.PO, val=1)
    assert str1.uid != strm1.uid != s1.uid
